# Generated by Django 4.2.5 on 2023-11-19 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workout_log', '0002_alter_exercise_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('focus', models.CharField(choices=[('Push', 'Push'), ('Pull', 'Pull'), ('Legs', 'Legs'), ('Upper', 'Upper'), ('Lower', 'Lower'), ('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('BC', 'Back-Chest'), ('SA', 'Shoulders-Arms')], max_length=10)),
                ('time_est_min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date_created', models.DateField()),
                ('split', models.CharField(choices=[('Arnold', 'Arnold'), ('Bro', 'Bro'), ('PPL', 'Push-Pull-Legs'), ('UL', 'Upper-Lower')], max_length=6)),
                ('is_synchronous', models.BooleanField()),
                ('lower_limit_min', models.FloatField()),
                ('upper_limit_min', models.FloatField()),
                ('is_muscle_focused', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlannedSets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('time_est_min', models.FloatField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_designer.day')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='workout_log.exercise')),
            ],
            options={
                'verbose_name_plural': 'planned sets',
            },
        ),
        migrations.AddField(
            model_name='day',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_designer.routine'),
        ),
    ]
