# Generated by Django 4.2.5 on 2023-11-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_designer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='focus',
            field=models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('LEGS', 'Legs'), ('UPPER', 'Upper'), ('LOWER', 'Lower'), ('CHEST', 'Chest'), ('BACK', 'Back'), ('SHOULDERS', 'Shoulders'), ('ARMS', 'Arms'), ('BC', 'Back-Chest'), ('SA', 'Shoulders-Arms'), ('REST', 'Rest')], max_length=10),
        ),
    ]
