# Generated by Django 4.2.5 on 2023-11-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_designer', '0003_daytype_remove_day_focus_alter_routine_split_focus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='workout_designer.daytype'),
        ),
    ]
