# Generated by Django 4.2.5 on 2023-11-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_designer', '0005_auto_20231121_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='name',
        ),
    ]
