# Generated by Django 4.2.5 on 2023-11-25 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workout_designer', '0006_remove_routine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='date_created',
        ),
        migrations.AddField(
            model_name='routine',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
