# Generated by Django 4.2.5 on 2023-10-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('name', 'equipment')},
        ),
    ]
