# Generated by Django 4.2.5 on 2023-11-21 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_log', '0003_alter_exercise_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='isCompound',
            new_name='is_compound',
        ),
        migrations.RenameField(
            model_name='muscleworked',
            old_name='directlyTargets',
            new_name='directly_targets',
        ),
    ]
