# Generated by Django 4.2.5 on 2023-11-05 01:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contains',
            options={'verbose_name_plural': 'contains'},
        ),
        migrations.RenameField(
            model_name='dailyweight',
            old_name='user',
            new_name='logged_by',
        ),
        migrations.AlterUniqueTogether(
            name='dailyweight',
            unique_together={('logged_by', 'date')},
        ),
    ]
