# Generated by Django 4.2.5 on 2023-11-06 21:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition_log', '0002_alter_contains_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyweight',
            old_name='logged_by',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='dailyweight',
            unique_together={('user', 'date')},
        ),
    ]
