# Generated by Django 4.2.5 on 2023-11-21 19:29
#  This script creates some initial data for the Nutrition Log.

# Once this script is migrated, modifications won't be saved 
#  (even after running migrate again)!! :/

from django.db import migrations


PROTEIN = "Protein"
CARBS = "Carbohydrates"
FATS = "Fats"


def create_initial_data(apps, schema_editor):
    # Create base macronutrients as food items
    food_items = apps.get_model('nutrition_log', 'FoodItem').objects
    food_items.create(name=PROTEIN)
    food_items.create(name=CARBS)
    food_items.create(name=FATS)

    # Create units for each food item
    units = apps.get_model('nutrition_log', 'Unit').objects
    units.create(name="1 g", calsPerUnit=4, proPerUnit=1, carbsPerUnit=0, fatsPerUnit=0, food_item=food_items.get(name=PROTEIN))
    units.create(name="1 g", calsPerUnit=4, proPerUnit=0, carbsPerUnit=1, fatsPerUnit=0, food_item=food_items.get(name=CARBS))
    units.create(name="1 g", calsPerUnit=9, proPerUnit=0, carbsPerUnit=0, fatsPerUnit=1, food_item=food_items.get(name=FATS))
    

class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_log', '0005_rename_targetcalories_goals_target_calories'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
